Repository autovance/style, pull requests merged in 2019-06, with the labels that each got.

#1 feat(typescript): allow no explict return type
  typescript.js
Labels: enhancement

#2 fix(typescript): turn off rules that are handled by types
  common.js
  javascript.js
  package-lock.json
  package.json
  typescript.js
Labels: bug, help wanted

#3 feat(common): add rules to prefer modern syntax
  common.js
Labels: feature
