Repository autovance/style, pull requests merged in 2020-01, with the labels that each got.

#5 chore: array-callback-returns should be an error
  javascript.js
Labels: chore

#7 fix: turn off no-unused-vars for hybrid projects
  index.js
  typescript.js
Labels: bug

#8 Merge pull request #8 from autovance/no-return-await
  common.js
Labels: feature

#10 Merge pull request #10 from autovance/disallow-promise-catch
  common.js
Labels: feature

#9 feat: require-await
  common.js
  index.js
  typescript.js
Labels: discussion, feature

#11 fix: correct warn setting
  common.js
  index.js
  typescript.js
Labels: bug
